name: check-pr
on:
  pull_request:
    branches:
      - master    
      - develop
    types: ['opened', 'reopened', 'synchronize']
  

permissions: write-all
   
jobs:
  check-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: |
          echo PR labeled in ${{ github.event.pull_request.base.ref }}
          exit 1
          
  toggle-enable:
    name: Toggle enable
    uses: ./.github/workflows/reusable.yml
    with:
      enable: false

  on-failure:
    needs: [check-1,toggle-enable]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: job failed
        run: |
          echo Do something with the failure

      
      
