name: check-pr
on:
  pull_request:
    branches:
      - master    
      - develop
    types: ['opened', 'reopened', 'synchronize']
  

permissions: write-all
   
jobs:
  check-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: |
          echo PR labeled in ${{ github.event.pull_request.base.ref }}
          echo testing
          
  toggle-enable:
    needs: [check-1]
    name: Toggle enable
    uses: ./.github/workflows/reusable.yml
    with:
      enable: false

  on-success:
    needs: [check-1,toggle-enable]
    if: ${{ !failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify success via slack
        id: slack
        run: echo "Worflow completed sucessfully"
        
  on-failure:
    needs: [check-1,toggle-enable]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: job failed
        run: |
          echo "Job status: ${{ job.status }}"

      
      
