name: Job - Test
on:
  schedule:
    # Minute[0-59] Hour[0-23] DayOfTheMonth[1-31] MonthOfTheYear[1-12] DayOfTheWeek([0-6] with 0=Sunday)
    - cron: '40 17 * * *'

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |-
          JOB_EXECUTOR=${{ github.actor }}
          echo "Job triggered by ${JOB_EXECUTOR} has been passed."
