name: Check - Merge Queue
on:
  pull_request:
    branches:
      - master      
      - develop
    types:
      - labeled
  workflow_run:
    workflows: 
      - check-1
    types: [completed]   

permissions: write-all
   
jobs:
  merge-queue-pr-trigger:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo pr base ref ${{ github.event.pull_request.base.ref }}
          echo pr number ${{ github.event.pull_request.number }}
          echo ${{ github.event.pull_request.base.ref || github.event.workflow_run.pull_requests[0].base.ref }}
          

  merge-queue-workflow-trigger:
    if: ${{ github.event_name == 'workflow_run' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The PR id that triggered this workflow is ${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "The base ref of the pull request that triggered this workflow is ${{ github.event.workflow_run.pull_requests[0].base.ref }}"
          echo "There are ${{ github.event.workflow_run.pull_requests[1].number }} PRs related to this workflow_run"
          echo ${{ github.event.pull_request.base.ref || github.event.workflow_run.pull_requests[0].base.ref }}

