name: Check - Merge Queue
on:
  pull_request:
    branches:
      - master      
      - develop
    types:
      - closed
      - opened
      - reopened

permissions: write-all
   
jobs:
  merge-queue-pr-trigger:
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'bug') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo pr number ${{ github.event.pull_request.number }}
          echo pr id ${{ github.event.pull_request.id }}
          echo pr status ${{ github.event.pull_request.closed }}
          echo ${{ contains(github.event.pull_request.labels.*.name, 'bot:merging') }}
      - name: Remove bot:merging label
        if: github.event_name == 'pull_request' && github.event.action == 'closed' # add this line to only run the step when the PR is closed
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: bug
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}          
          
