# This script will return true if the current hour in EST timezone matches the hour provided in the input parameter
# This is useful for scheduled jobs as they are set using UTC and github does not support timezone in cron jobs.
#   so when EST timezone is in daylight savings time it is 4 hours behind UTC and when it is not it is 5 hours behind UTC, 
#   and our jobs would run at the wrong time.
name: Reusable - Check Hour Matches Current hour in EST Timezone
on:
  workflow_call:
    inputs:
      hour:
        required: true
        description: hour in EST timezone in the format 24h (e.g. 17 for 5pm)
        type: string

    outputs:
      hourMatches:
        description: "Whether the hour match the hour in EST timezone"
        value: ${{jobs.validate-east-hour.outputs.hour-matches}}
jobs:
  validate-east-hour:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      hour-matches: ${{steps.check-hour.outputs.result}}
    steps:
      - name: 'Validate whether hour ${{ inputs.hour }} matches current hour in EST timezone'
        uses: actions/github-script@v6
        id: check-hour
        with:
          result-encoding: string
          script: | 
              const date = new Date();
              const formatter = new Intl.DateTimeFormat('en-US', {
                hour: 'numeric',
                hour12: false,
                timeZone: 'Canada/Eastern'
              });
              const currentHour = formatter.format(date);
              console.log(`Current EST hour: ${currentHour}`);

              const result = currentHour === "${{ inputs.hour }}";
              console.log(`result: ${result}`);

              return result;
