# This script will return true if the current hour in EST timezone matches the hour provided in the input parameter
# This is useful for scheduled jobs as they are set using UTC and github does not support timezone in cron jobs.
#   so when EST timezone is in daylight savings time it is 4 hours behind UTC and when it is not it is 5 hours behind UTC, 
#   and our jobs would run at the wrong time.
name: Reusable - Check Hour Matches Current hour in EST Timezone
on:
  workflow_call:
    inputs:
      hour:
        required: true
        description: hour in EST timezone in the format 24h (e.g. 17 for 5pm)
        type: string

    outputs:
      hourMatches:
        description: "Whether the hour match the hour in EST timezone"
        value: ${{jobs.validate-east-hour.outputs.hour-matches}}
jobs:
  validate-east-hour:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      hour-matches: ${{steps.check-hour.outputs.hour-matches}}
    steps:
      - name: 'Validate whether hour ${{ inputs.hour }} matches current hour in EST timezone'
        id: "check-hour"
        run: |
          set -e
          hour_provided=${{ inputs.hour }}
          hour_matches=false

          est_hour=$(date -d 'TZ="America/Thunder_Bay" now' +%H)
          
          if [[ "${est_hour]" == "${hour_provided]" ]]; then
            hour_matches=true
          fi

          echo "hour-matches=$hour_matches" >> $GITHUB_OUTPUT  
