name: Reusable 
on:
  workflow_call:
    inputs:
      enable:
        required: true
        type: boolean
      text:
        required: false
        type: string
        description: type any string to test

permissions: write-all

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
    - id: toggle
      run: |-
        echo "Enabled: ${{ inputs.enable }}"
    - name: testing 
      run: |
        echo ${{ inputs.text }}
        
  
