name: 1. Run - Garden commands 
on:
  workflow_dispatch:
  ## LIMIT OF 10 INPUTS
    inputs:
      text:
        type: string
        description: type any string
        required: false

permissions: write-all

jobs:
  test:
    name: Testing
    uses: ./.github/workflows/reusable.yml
    with:
      enable: false
      text: ${{ github.event.inputs.text }}
