name: 1. Run Test
on:
  workflow_dispatch:
  ## LIMIT OF 10 INPUTS
    inputs:
      text:
        type: string
        description: type any string
        required: false

permissions: write-all

jobs:
  check-est-hour:
    name: Check daylight saving time
    uses: ./.github/workflows/reusable-check-hour.yml
    with:
      hour: 13

  test-1:
    needs: [check-est-hour]
    if: ${{ inputs.text == '1' && needs.check-est-hour.outputs.hourMatches == 'true' }}
    name: Testing 1
    uses: ./.github/workflows/reusable.yml
    with:
      enable: false
      text: ${{ github.event.inputs.text }}
      
  test-2:
    if: ${{ inputs.text == '2' && needs.check-est-hour.outputs.hourMatches == 'true' }}
    runs-on: ubuntu-latest
    name: Testing 2
    steps:
      - name: Print
        run: |
          exit 1;

  test-3:
    needs: [test-2]
    runs-on: ubuntu-latest
    name: Testing 3
    steps:
      - name: Print
        run: |
          echo enter
      
  print:
    needs: [test-1, test-2]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    name: Printing
    steps:
      - name: Print
        run: |
          echo Printing something
      
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Create github authentication token
  #     uses: gliech/create-github-secret-action@v1.4.10
  #     with:
  #       name: ACCESS_TOKEN
  #       value: 123
  #       pa_token: ${{ secrets.CAROL_ACCESS_TOKE }} 
