name: 1. Run - Garden commands 
on:
  workflow_dispatch:
  ## LIMIT OF 10 INPUTS
    inputs:
      text:
        type: string
        description: type any string
        required: false

permissions: write-all

jobs:
  #test:
  #   name: Testing
  #   uses: ./.github/workflows/reusable.yml
  #   with:
  #     enable: false
  #     text: ${{ github.event.inputs.text }}
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Create github authentication token
      uses: gliech/create-github-secret-action@v1.4.10
      with:
        name: ACCESS_TOKEN
        value: 123
        pa_token: ${{ secrets.CAROL_ACCESS_TOKE }} 
