name: Check - Merge Queue
on:
  pull_request:
    branches:
      - develop      
    types:
      - ['opened', 'reopened', 'synchronize']
  

permissions: write-all
   
jobs:
  merge-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: echo "Branch name: ${{ github.head_ref }}"
      
