name: check-1
on:
  pull_request:
    branches:
      - master      
    types: ['opened', 'reopened', 'synchronize']
  

permissions: write-all
   
jobs:
  check-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: |
          echo run check-1
      
