name: Check - Merge Queue
on:
  pull_request:
    branches:
      - master      
    types: ['opened', 'reopened', 'synchronize']
  

permissions: write-all
   
jobs:
  merge-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: |
          echo "Branch name: ${{ github.head_ref }}"
      
