# Update develop branch from master every time a push is done in master branch
name: Check - Update Develop Branch
on:
  push:
    branches:
      - master-test

jobs:
  update-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop-test
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update Develop Branch
          body: |
            This pull request updates the develop branch with changes from the master branch.
          branch: develop-test
          commit-message: Update Develop Branch
          delete-branch: true
